package open.dolphin.infomodel;
// Generated 2010/06/30 10:57:59 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import open.dolphin.queries.DolphinQuery;

/**
 * 施設 MEMO:マッピング d_facility
 * FacilityModel generated by hbm2java
 */
public class FacilityModel extends InfoModel {

    private long id;//MEMO:Refrection
    private String facilityId;//施設ID MEMO:Refrection
    private String facilityName;//施設名 MEMO:Refrection
    private String zipCode;//郵便番号 MEMO:Refrection
    private String address;//住所 MEMO:Refrection
    private String telephone;//電話番号 MEMO:Refrection
    private String url;//MEMO:Refrection
    private Date registeredDate;//登録日 MEMO:Refrection
    private String memberType;//メンバータイプ MEMO:Refrection

    /**
     *
     */
    public FacilityModel() {
    }

    /**
     * 検索 MEMO:何もしない
     * @param query
     * @return false
     */
    @Override
    public boolean search(DolphinQuery query) {
        return false;
    }

    /**
     * idのGetter
     * MEMO:Refrection
     * @return id
     */
    public long getId() {
        return this.id;
    }

    /**
     * idのSetter
     * MEMO:Refrection
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * 施設IDのGetter
     * MEMO:Refrection
     * @return 施設ID
     */
    public String getFacilityId() {
        return this.facilityId;
    }

    /**
     * 施設IDのSetter
     * MEMO:Refrection
     * @param facilityId 施設ID
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }

    /**
     * 施設名のGetter
     * MEMO:Refrection
     * @return 施設名
     */
    public String getFacilityName() {
        return this.facilityName;
    }

    /**
     * 施設名のSetter
     * MEMO:Refrection
     * @param facilityName 施設名
     */
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }

    /**
     * 郵便番号を返す。
     * MEMO:Refrection
     * @return 郵便番号
     */
    public String getZipCode() {
        return this.zipCode;
    }

    /**
     * 郵便番号を設定する。
     * MEMO:Refrection
     * @param zipCode 郵便番号
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * 住所のGetter
     * MEMO:Refrection
     * @return 住所
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * 住所のSetter
     * MEMO:Refrection
     * @param address 住所
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * 電話番号のGetter
     * MEMO:Refrection
     * @return 電話番号
     */
    public String getTelephone() {
        return this.telephone;
    }

    /**
     * 電話番号のSetter
     * MEMO:Refrection
     * @param telephone 電話番号
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * urlのGetter
     * MEMO:Refrection
     * @return url
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * urlのSetter
     * MEMO:Refrection
     * @param url url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 登録日のGetter
     * MEMO:Refrection
     * @return 登録日
     */
    public Date getRegisteredDate() {
        return this.registeredDate;
    }

    /**
     * 登録日のSetter
     * MEMO:Refrection
     * @param registeredDate 登録日
     */
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

    /**
     * メンバータイプのGetter
     * MEMO:Refrection
     * @return メンバータイプ
     */
    public String getMemberType() {
        return this.memberType;
    }

    /**
     * メンバータイプのSetter
     * MEMO:Refrection
     * @param memberType メンバータイプ
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     *
     * @return
     */
    @Override
    public int hashCode() {
        final int PRIME = 31;
        int result = 1;
        result = PRIME * result + (int) (id ^ (id >>> 32));
        return result;
    }

    /**
     *
     * @param obj obj
     * @return
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FacilityModel other = (FacilityModel) obj;
        if (getId() != other.getId()) {
            return false;
        }
        return true;
    }
}
