package open.dolphin.infomodel;
// Generated 2010/06/30 10:57:59 by Hibernate Tools 3.2.1.GA

/**
 * 観察データ MEMO:マッピング  d_observation
 * ObservationModel generated by hbm2java
 */
public class ObservationModel extends KarteEntryBean {

    private String observation;//MEMO:Refrection
    private String phenomenon;//MEMO:Refrection
    private String value;//MEMO:Refrection
    private String unit;//MEMO:Refrection
    private String categoryValue;//MEMO:Refrection
    private String valueDesc;//MEMO:Refrection
    private String valueSys;//MEMO:Refrection
    private String memo;//MEMO:Refrection

    /**
     *
     */
    public ObservationModel() {
    }

    /**
     * observationのGetter
     * MEMO:Refrection
     * @return observation OBSERVATION_ALLERGY = "Allergy" OBSERVATION_BLOODTYPE = "Bloodtype" OBSERVATION_INFECTION = "Infection" OBSERVATION_LIFESTYLE = "Lifestyle" OBSERVATION_PHYSICAL_EXAM = "PhysicalExam"
     */
    public String getObservation() {
        return this.observation;
    }

    /**
     * observationのSetter
     * MEMO:Refrection
     * @param observation OBSERVATION_ALLERGY = "Allergy" OBSERVATION_BLOODTYPE = "Bloodtype" OBSERVATION_INFECTION = "Infection" OBSERVATION_LIFESTYLE = "Lifestyle" OBSERVATION_PHYSICAL_EXAM = "PhysicalExam"
     */
    public void setObservation(String observation) {
        this.observation = observation;
    }

    /**
     * phenomenonのGetter
     * MEMO:Refrection
     * @return phenomenon PHENOMENON_BODY_HEIGHT = "bodyHeight" PHENOMENON_BODY_WEIGHT = "bodyWeight" PHENOMENON_TOBACCO = "tobacco" PHENOMENON_ALCOHOL = "alcohol" PHENOMENON_OCCUPATION = "occupation"
     */
    public String getPhenomenon() {
        return this.phenomenon;
    }

    /**
     * phenomenonのSetter
     * MEMO:Refrection
     * @param phenomenon PHENOMENON_BODY_HEIGHT = "bodyHeight" PHENOMENON_BODY_WEIGHT = "bodyWeight" PHENOMENON_TOBACCO = "tobacco"
     */
    public void setPhenomenon(String phenomenon) {
        this.phenomenon = phenomenon;
    }

    /**
     * valueのGetter
     * MEMO:Refrection
     * @return
     */
    public String getValue() {
        return this.value;
    }

    /**
     * valueのSetter
     * MEMO:Refrection
     * @param value
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * unitのGetter
     * MEMO:Refrection
     * @return unit UNIT_BODY_WEIGHT = "Kg" UNIT_BODY_HEIGHT = "cm"
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * unitのSetter
     * MEMO:Refrection
     * @param unit UNIT_BODY_WEIGHT = "Kg" UNIT_BODY_HEIGHT = "cm"
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * categoryValueのGetter
     * MEMO:Refrection
     * @return
     */
    public String getCategoryValue() {
        return this.categoryValue;
    }

    /**
     * categoryValueのSetter
     * MEMO:Refrection
     * @param categoryValue
     */
    public void setCategoryValue(String categoryValue) {
        this.categoryValue = categoryValue;
    }

    /**
     * valueDescのGetter
     * MEMO:Refrection
     * @return
     */
    public String getValueDesc() {
        return this.valueDesc;
    }

    /**
     * valueDescのSetter
     * MEMO:Refrection
     * @param valueDesc
     */
    public void setValueDesc(String valueDesc) {
        this.valueDesc = valueDesc;
    }

    /**
     * valueSysのGetter
     * MEMO:Refrection
     * @return
     */
    public String getValueSys() {
        return this.valueSys;
    }

    /**
     * valueSysのSetter
     * MEMO:Refrection
     * @param valueSys
     */
    public void setValueSys(String valueSys) {
        this.valueSys = valueSys;
    }

    /**
     * memoのGetter
     * MEMO:Refrection
     * @return
     */
    public String getMemo() {
        return this.memo;
    }

    /**
     * memoのSetter
     * MEMO:Refrection
     * @param memo
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}
